# Site settings
title: Jorgen Wu
email: wujorgen@gmail.com
url: https://www.linkedin.com/in/jorgen-wu/
description: "Jorgen Wu's personal site. Welcome!"
keywords: Jorgen Wu, Jorgen, Wu
skills: "Engineer - Programmer - Musician<br>Thanks for stopping by!"
meta_author: Wu Jorgen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 222222 #18bc9c #80B3FF
  primary-rgb: "128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jorgen Wu
  location: Location
  social: Around the Web
  credits: Get In Touch

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jorgen-wu/
  - title: github
    url: http://github.com/wujorgen

# Postal address (add as many lines as necessary)
address:
  - line: At home. :)
  - line: 

# Credits content
credits: "Feel free to reach out. Let's connect. :)"

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
